title: Cain's Blog
subtitle: Cain's Tech Blog
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.jpg
disqus_shortname: cain19811028  #for comments using disqus
author: cain19811028
author_bio: #Hello, my name is John Doe.I am an award winning Full Stack Web Developer and UI/UX Javascript specialist.Check out my blog articles, React.JS and Vue.JS UI components at the code laboratory.Feel free to take a look at my latest projects below.Based in London, UK. 
author_email: "cain19811028@gmail.com"
author_location: Taiwan
author_website_url: "https://cain19811028.github.io"

# social links
github_username: cain19811028
facebook_username: cain19811028
medium_username: cain19811028 
linkedin_username: cain-chen-5a984443
behance_username: yourusername
instagram_username: yourusername
telegram_username: yourusername
dribbble_username: yourusername 
flickr_username: yourusername
twitter_username: yourusername

# title: Cain's Tech Blog
# author: cain19811028
# email: cain19811028@domain.com
# description: > # this means to ignore newlines until "show_exerpts:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# show_excerpts: true # set to true to show excerpts on the homepage

# # Minima date format
# # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
# sass:
#   sass_dir: _sass

# plainwhite:
#   name: Cain
#   tagline: Developer
#   date_format: "%b %-d, %Y"

#   # generate social links in footer
#   social_links:
#     github:  cain19811028
#     facebook: cain19811028
#     linkedIn: cain-chen-5a984443
#     rss: rss
#     # twitter: cain19811028
#     # dribbble: jekyll
#     # flickr:   jekyll
#     # instagram: jekyll
#     # pinterest: jekyll
#     # youtube: jekyll
#     # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
#     # youtube_channel_name: CloudCannon
#     # telegram: jekyll
#     # googleplus: +jekyll
#     # microdotblog: jekyll

#     # Mastodon instances
#     # mastodon:
#     # - username: jekyll
#     #   instance: example.com
#     # - username: jekyll2
#     #   instance: example.com

# # If you want to link only specific pages in your header, uncomment
# # this and add the path to the pages in order as they should show up
# #header_pages:
# # - about.md

# # Build settings
# remote_theme: thelehhman/plainwhite-jekyll

# plugins:
#   - jekyll-seo-tag